### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by nghivo94**
In this PR, I restructured the notebooks and exported modules into different sections as described in #77 . The modified module and notebooks directory structures now are:

image

And documentation also includes these sections:

image

This is a partial (early) PR to demonstrate the main sections. Many notebooks in these sections will be further modified to demonstrate layering and unifying formats.

### CODE REVIEW

**Comment by nghivo94** [comment]
I am half-way through the documentation and restructuring tasks listed in #77 . I have reworked the `core` and `vision` module, with all legacy code being completely removed from `vision` notebooks. Notebooks are still duplicated in `core` to avoid importing with legacy code from other modules, but the newly added, reworked notebooks include `01_fn_exec`, `02_fn_to_schema`, `03_oas_to_schema`.

In general, new reworked notebooks are documented as Experiment section (s) -> (optionally separated) Modularized function with  manual testing -> Simulated GPT workflow.

@doyu @linhktran Could you start reviewing these reworked notebooks, especially the `vision` module?

**Comment by doyu** [comment]
Sorry for the late review. Looks quite OK but a few points:

- shoud have deleted:    llmcam/core/oas_to_fc.py?

```python
llmcam/application/chat_ui.py:from ..core.fn_to_fc import capture_youtube_live_frame_and_save, ask_gpt4v_about_image_file
llmcam/application/chat_ui.py:from ..core.fn_to_fc import tool_schema, complete, form_msg                
llmcam/application/chat_ui.py:from ..utils.store import add_api_tools, add_function_tools, remove_tools  
llmcam/application/chat_ui.py:from ..utils.store import execute_handler_core, handler_schema
llmcam/application/chat_ui.py:from ..vision.yolo import detect_objects
```
- Why `..core/fn_to_fc `? 
- Also should be `import *`?
- Do we really need chat web sockets since htmx hotswap can replace the element without server communication?

**Comment by nghivo94** [comment]
Here is some updates on your comments:

- [ ] shoud have deleted: llmcam/core/oas_to_fc.py?
- [ ] Why ..core/fn_to_fc ?
- [ ] Also should be import *?

> Do we really need chat web sockets since htmx hotswap can replace the element without server communication?

We need web sockets because we are updating htmx piece-by-piece. This updating method lets the user's message to be displayed first without waiting for GPT response.

**Comment by doyu** [comment]
>> Do we really need chat web sockets since htmx hotswap can replace the element without server communication?
> 
> We need web sockets because we are updating htmx piece-by-piece. This updating method lets the user's message to be displayed first without waiting for GPT response.

Probably that's not true since htmx is just java script wrapper, some of their syntax can update the element without server communication as normal javascript updates DOM.

https://chatgpt.com/share/6760430f-360c-8002-966f-ff511c3ec568

**Comment by doyu** [comment]
As explained today, this lecture needs some target, what do you want to deliver to the audience? We don't need slides but you could explain with notebooks. You may also want some block diagram of modules / layers, sequence diagram of gpt function calling, server instanciations, notification mechanism to explain. It's upto you but just make sure some of the audience are not familar with llmcam / gpt / FC. They would need some introduction. Anyway, knowing gpt programming would be useful for anyone. Again, this is a communication!

**Review by doyu — APPROVED** [review]

**Pull request merged**
