### PR TITLE
OAS to Requests

### PR DESCRIPTION
**Pull request by nghivo94**
In this PR, I developed on our previous work to let GPT generate and execute requests based on OAS file. In particular, these are the important functions and modifications to our existing function:

- Function `extract_refs` to recursively extracts and flattens schemas used in OAS (`components`)
- Function `transform_property` to transform OAS schemas into GPT-compatible schemas by transferring all the common fields, adjusting the mismatched fields, and appending all extra fields into schema description.
- Function `toolbox_schema` to generate extensive tools schema from OAS to GPT function calling by extracting function names, descriptions, and setting parameters including five major fields (`url`, `method`, `path` - path parameters, `query` - query parameters, `body` - request body).
- Function `generate_request` to generate and execute requests from GPT function calling
- Modifications to `fn_exec`, `fn_result_content`, and `complete` to pass in toolbox schema to `aux_fn` (in this case, `generate_request`)

### CODE REVIEW

**Review by doyu — APPROVED** [review]
Can the tool schema problem be solved with **structured output**?
https://openai.com/index/introducing-structured-outputs-in-the-api/

**Comment by nghivo94** [comment]
Are you referring to the circular definition with DigiTraffic or OAS -> GPT compatibility issue? At least as of now there are no problems that require structuring the output of functions.

**Comment by doyu** [comment]
> OAS -> GPT compatibility issue

This one!

I was considering the possibility of making use of structured output decreasing our code of this part...

**Comment by nghivo94** [comment]
I don't think it is exactly related. Tool schema is defined at the start to describe the inputs and function name, while this seems to help with the outputs only. In the PR, OAS -> GPT compatibility issue I encountered was the mismatching fields between OAS definitions and GPT definitions of the function and parameters. For example, GPT only recognizes some fields (`type`, `description`, `default`) while OAS can have more descriptive fields, or `required` field of GPT is a list of required child properties while that of OAS is whether the parent property is required. But the structured outputs seem to be a simple parser of final tool outputs instead. 

On the other hand, we can consider about this when trying to combine different functions in sequence, e.g., capture youtube live -> extract live information or between different services.

**Comment by doyu** [comment]
> On the other hand, we can consider about this when trying to combine different functions in sequence, e.g., capture youtube live -> extract live information or between different services.

That's the part I'm expecting that gpt reasoning automatically to sort out, not by explict programming🤔️

**Pull request merged**
