### PR TITLE
OAS->FC and demo of automated function calling with GPT

### PR DESCRIPTION
**Pull request by linhktran**
The demo is modified to be compatible with nbdev and shows a nice example of how automated function calling can be performed.

### CODE REVIEW

**Review by doyu — CHANGES_REQUESTED** [review]
Probably it's better to split this PR into 2 PRs.
One for function -> FC
Another for OAS -> FC

fail_* files are not needed to include here.

Haven't `nbdev_prepare geneate `llmcam` pacakge as @nghivo94 instructed in README?

**Comment by linhktran** [comment]
I am not sure why my `nbdev_prepare` cannot make it as Nghi describes. It somehow always shows this first markdown line that looks quite weird. I even rewrite the branch with origin/main but whenever I use `nbdev_prepare` it appears agai.

**Comment by doyu** [comment]
Please use only necesary commits in a PR after rebasing onto `origin/main` branch.
Also if possible, please try to make use of some existing features from other modules as much as possible.

**Review by doyu — CHANGES_REQUESTED** [review]
The final outcome looks too good to me, but each commit does unnecessary adding files & deleting files, as seen here,  https://asciinema.org/a/688108. You can clean up those unnecesary file add/delelte with editing `git rebase -i ` & choose <edit>.

**Comment by doyu** [comment]
@linhktran can you finish this first?

**Pull request closed without merging**
